- hosts: [cs-test]
  tasks:
    - name: add a dir and set permissions
      file:
        path: /etc/1qazxsw2
        owner: ec2-user
        group: ec2-user
        mode: 0755
        state: directory
      become: yes
    - name: remove the dir you just added
      file:
        path: /etc/1qazxsw2
        state: absent
      become: yes
